# Generated by Django 3.2.16 on 2026-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-pub_year',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('film', 'Фильм'), ('series', 'Сериал'), ('game', 'Игры')], max_length=20, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
