# Generated by Django 3.2.16 on 2026-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20260317_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('film', 'Фильм'), ('series', 'Сериал'), ('games', 'Игры')], max_length=20, verbose_name='Категория'),
        ),
    ]
